[package]
name = "clock"
version = "0.1.0"
authors = ["recombinant <gituser@recombinant.me.uk>"]

[target.'cfg(windows)'.dependencies]
winapi = { version = "*", features = ["libloaderapi", "sysinfoapi", ] }
extras = { path = "../../extras" }
